// Sterling at Silver Springs — Edge Function: Newsletter AI Generator (v2)
// Deploy: supabase functions deploy generate-newsletter
// Deno runtime
//
// Response shape (backward-compat):
//   { html: "<full bulletin HTML>", newsletter: { headline, tagline, sections, callToAction, closingMessage } }
// HTML is generated by Claude using the bulletin system prompt.
// `newsletter` is derived deterministically from intake (no second LLM call) so the
// legacy frontend keeps rendering until the Lovable migration ships.

import { serve } from "https://deno.land/std@0.177.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const SYSTEM_PROMPT = `You are a Newsletter Bulletin Generator. You produce one-page printed-style news bulletins, NOT long-form blog posts.

# OUTPUT FORMAT

Return a single self-contained HTML document. No external CSS, no external JS, all styles inline or in a <style> block in <head>. Print-friendly @media print rules included. Page size A4/Letter equivalent, max 2 pages, target 1 page.

# VISUAL STRUCTURE (locked)

1. HEADER BAND
   - Centered org name in large bold serif or strong sans-serif (color: BRAND_PRIMARY)
   - One line below: "[Issue Month] [Year] [Org Type] Newsletter" in smaller weight
   - Optional logo top-left if LOGO_URL provided
   - Thin horizontal rule under the header

2. SECTION BLOCKS (repeating)
   Each section follows this exact pattern:
   - Colored title bar: full-width, BRAND_PRIMARY background, white bold text, ~6px vertical padding, left-aligned title
   - Body area directly under the bar with light gray top/bottom borders
   - Body uses 1 column OR 2 columns depending on content density (see SECTION TYPES below)
   - 8-12px vertical spacing between sections, no hero whitespace

3. FOOTER (every page)
   - Left: "[Org Name] - [Issue Month] [Year]"
   - Right: "Page X" (auto-numbered)
   - Thin top border, small gray text

# SECTION TYPES (pick what applies based on input)

A) UPDATES BLOCK (2-column)
   - Left column: 2-4 short updates, each with a bold sub-heading and 1-3 sentence blurb
   - Right column: contact emails, links, or follow-up info as a labeled list
   - Use when the input mentions news, announcements, board actions, project updates

B) MEETING / EVENT DETAIL (1-column, dense)
   - Inline labels: Date, Time, Executive Session, Location, Notes
   - One short paragraph max
   - Use for board meetings, single events with logistical detail

C) EVENTS CALENDAR (table)
   - 3-column table: Date | Event | Time
   - Alternating row shading (very light gray)
   - Optional 1-line reminder under the table in smaller text
   - Use whenever 3+ events/dates are mentioned

D) REMINDERS (2-column or 1-column)
   - Each item: bold short label + 1-2 sentence blurb
   - 4-6 items max
   - Use for fees, hours, policies, recurring items

E) CALL TO ACTION (compact)
   - Small bordered box, NOT full-width hero
   - Bold one-line headline + 1 sentence + email/link
   - Use sparingly, max 1 per bulletin

F) CONTACTS DIRECTORY (2-column)
   - Left column: management/main contact block (org, address, phone, email, hours)
   - Right column: "Who to Contact" - role-based list (e.g., "Pool issues: Brian Douglas - brian@...")
   - Use whenever contact info is provided

G) DATA TABLE (1-column, full width)
   - Use for financials, stats, performance numbers, KPIs
   - Colored header row matching BRAND_PRIMARY
   - Right-align numbers, bold totals
   - If financials are large, push to page 2 alone with "Continued" subhead

# DENSITY RULES

- No paragraph longer than 4 sentences. Cut to 2 if possible.
- No section longer than 8 lines of body text on screen.
- If content overflows page 1, the LAST section moves to page 2. Never split a section across pages.
- No emojis. No icons unless LOGO_URL is provided.
- No marketing fluff, no hype words, no exclamation points unless the input had them.
- News-bulletin voice: factual, scannable, dated, named. Real people, real numbers, real dates.

# INPUT MAPPING

You receive these intake fields:
- newsletter_title -> header line 1 (org name)
- issue_date -> header line 2 (e.g., "May 2026")
- topic -> primary subject angle, drives section emphasis
- target_audience -> tone calibration only (homeowners = neighborly factual; members = mission-aligned; customers = service-oriented)
- description -> parse for: announcements, names, dates, dollar amounts, contacts, events, action items. Distribute across sections A-G.
- keywords -> light SEO/topical reinforcement in section sub-heads
- brand_primary (hex) -> all colored bars, header text, table headers
- logo_url (optional) -> top-left of header band
- events[] (optional) -> populates section C
- contacts[] (optional) -> populates section F
- reminders[] (optional) -> populates section D
- financials[] (optional) -> populates section G on page 2
- cta (optional) -> populates section E

If a field is empty, skip the section. Never invent contacts, events, names, dollar amounts, or dates that weren't provided.

# WHAT NOT TO DO

- Do not produce one giant hero header with a long article underneath.
- Do not write blog-style intros ("In today's newsletter we'll cover...").
- Do not use sentimental sign-offs ("Warmest regards" only if present in input).
- Do not pad. If you only have 2 sections of real content, output 2 sections. A short bulletin is fine.
- Do not use generic stock phrases ("we're excited to announce", "stay tuned", "join us as we").
- Do not generate placeholder content. Empty input = skip the section.

# RETURN

Return only the HTML. No commentary, no markdown wrapper, no explanation.`;

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    const {
      title,
      topic,
      audience,
      description,
      keywords,
      issue_date,
      brand_primary,
      logo_url,
      events,
      contacts,
      reminders,
      financials,
      cta,
    } = body;

    const ANTHROPIC_KEY = Deno.env.get("ANTHROPIC_API_KEY");
    if (!ANTHROPIC_KEY) {
      throw new Error("ANTHROPIC_API_KEY is not configured on the function");
    }

    const intake = {
      newsletter_title: title || "",
      issue_date: issue_date || "",
      topic: topic || "",
      target_audience: audience || "",
      description: description || "",
      keywords: keywords || "",
      brand_primary: brand_primary || "#1f3864",
      logo_url: logo_url || null,
      events: events || [],
      contacts: contacts || [],
      reminders: reminders || [],
      financials: financials || [],
      cta: cta || null,
    };

    const userMessage = `Generate the bulletin HTML from this intake data:\n\n${JSON.stringify(intake, null, 2)}`;

    const claudeRes = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": ANTHROPIC_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5",
        max_tokens: 8000,
        system: [
          {
            type: "text",
            text: SYSTEM_PROMPT,
            cache_control: { type: "ephemeral" },
          },
        ],
        messages: [{ role: "user", content: userMessage }],
      }),
    });

    const claudeData = await claudeRes.json();

    if (!claudeRes.ok || claudeData.type === "error") {
      throw new Error(
        `Anthropic ${claudeRes.status}: ${claudeData.error?.message || JSON.stringify(claudeData)}`
      );
    }

    let html = claudeData.content[0].text.trim();
    // Some models occasionally wrap output in ```html ... ``` fences despite instructions; strip them.
    if (html.startsWith("```")) {
      html = html.replace(/^```(?:html)?\s*\n?/, "").replace(/\n?```\s*$/, "");
    }

    const newsletter = buildLegacyNewsletter(intake);

    return new Response(
      JSON.stringify({ html, newsletter }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

// Deterministic mapper from intake -> legacy { headline, tagline, sections, callToAction, closingMessage }
// shape so the existing Lovable frontend keeps rendering until it migrates to HTML.
function buildLegacyNewsletter(intake: Record<string, any>) {
  const sections: Array<{ heading: string; body: string }> = [];

  if (intake.description) {
    sections.push({ heading: "Community Update", body: intake.description });
  }

  if (Array.isArray(intake.events) && intake.events.length) {
    const lines = intake.events
      .map((e: any) => {
        if (Array.isArray(e)) {
          const [date, name, time] = e;
          return `${date || ""} — ${name || ""}${time ? ` (${time})` : ""}`.trim();
        }
        return `${e.date || ""} — ${e.name || e.event || ""}${e.time ? ` (${e.time})` : ""}`.trim();
      })
      .filter(Boolean)
      .join("\n");
    if (lines) sections.push({ heading: "Upcoming Events", body: lines });
  }

  if (Array.isArray(intake.reminders) && intake.reminders.length) {
    const lines = intake.reminders
      .map((r: any) => {
        if (Array.isArray(r)) return `${r[0] || ""}: ${r[1] || ""}`.trim();
        return `${r.label || ""}: ${r.blurb || r.body || ""}`.trim();
      })
      .filter(Boolean)
      .join("\n");
    if (lines) sections.push({ heading: "Reminders", body: lines });
  }

  if (Array.isArray(intake.contacts) && intake.contacts.length) {
    const lines = intake.contacts
      .map((c: any) => {
        if (Array.isArray(c)) {
          const [role, name, contact] = c;
          return `${role || ""} — ${name || ""}${contact ? ` (${contact})` : ""}`.trim();
        }
        const role = c.role || "";
        const name = c.name || "";
        const contact = c.email || c.phone || "";
        return `${role} — ${name}${contact ? ` (${contact})` : ""}`.trim();
      })
      .filter(Boolean)
      .join("\n");
    if (lines) sections.push({ heading: "Contacts", body: lines });
  }

  if (Array.isArray(intake.financials) && intake.financials.length) {
    const lines = intake.financials
      .map((f: any) => {
        if (Array.isArray(f)) return `${f[0] || ""}: ${f[1] ?? ""}`.trim();
        return `${f.name || f.account || ""}: ${f.amount ?? ""}`.trim();
      })
      .filter(Boolean)
      .join("\n");
    if (lines) sections.push({ heading: "Financial Summary", body: lines });
  }

  let callToAction = { text: "", instruction: "" };
  if (intake.cta) {
    callToAction = {
      text: intake.cta.headline || intake.cta.text || "Learn More",
      instruction: intake.cta.body || intake.cta.instruction || "",
    };
  }

  const tagline = intake.issue_date
    ? `${intake.issue_date}${intake.target_audience ? ` ${intake.target_audience}` : ""} Newsletter`
    : intake.topic || "";

  return {
    headline: intake.newsletter_title,
    tagline,
    sections,
    callToAction,
    closingMessage: "From the Board of Directors",
  };
}
